### ISSUE TITLE
Wrong credentials

### ISSUE THREAD

**Issue by kubinka0505** [acheong08/Diffusion-ColabUI#12]
Despite running the notebook correctly (public version) and logging with _HuggingSpace_ credentials I receive the `incorrect credentials` error, which shouldn't happen - obviously.

How can I fix this?

**Comment by 0xRETR0** [comment]
Can you elaborate a little? When exactly do you get the error? I'm a bit confused, because as far i know you don't need to input any credentials anywhere, aside from inside the gradio link. If that's where you're getting the error, then you've inputed the wrong creds; you can set them inside the colab, the default username is webui with the password diffusion.

**Comment by acheong08** [comment]
Why are you logging in with huggingface credentails? You get to set your own gradio username and password
