### ISSUE TITLE
Progress bar stuck and have to refresh

### ISSUE THREAD

**Issue by Enferlain** [acheong08/Diffusion-ColabUI#55]
Any idea how to fix this? Used to happen rarely on the previous colab but now it's like every 2nd generation

![image](https://user-images.githubusercontent.com/15861396/206525369-0aeb2d24-0ae4-4108-b136-12fb2eb87f0a.png)

**Comment by acheong08** [comment]
It is the exact same Colab, just stored in a different location. This is possibly due to slow internet or a new bug with https://github.com/AUTOMATIC1111/stable-diffusion-webui as it was recently updated (today morning). You can try deleting and restarting the runtime to see if it is an issue with gradio

**Comment by acheong08** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

A lot of issues seem to have been occurring recently

**Comment by Enferlain** [comment]
Do you know if it's possible to reset it without refreshing the entire page? It sucks when you're using inpaint especially

**Comment by misobarisic** [comment]
You can use shift+enter on the positive prompt box to make it generate new images. The bar will still be stuck but you don't have to refresh your tab
